# Site settings
title: maya richman
description: >
  I am Maya and this is my personal homepage.

baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://mayarichman.github.io" # the base hostname & protocol for your site

author:
  fullname: maya richman
  github: mayarichman
  twitter: mayarichman
  # disqus: your_disqus_username

# Handling Reading
exclude: ["README.md", "README.html"]

# Build settings
markdown: kramdown
timezone: Europe/Berlin
